import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { query, pool } from '../config/db.js';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, 'catalogue.sql');

/**
 * Snapshots the live store into src/db/catalogue.sql — `npm run db:export`.
 *
 * This is the developer half of the pair; `npm run db:seed-catalogue` is the
 * half that runs on a server. Re-run it whenever the catalogue changes
 * meaningfully and commit the result, so a fresh database can be brought up
 * without access to the source database.
 *
 * Only store content is exported. Customers, orders, carts, wishlists,
 * enquiries and redirects are runtime data and are deliberately left out.
 */

// Parent tables first: every row's foreign keys must already exist.
const TABLES = [
  'categories',
  'subcategories',
  'products',
  'product_images',
  'product_variants',
  'banners',
  'uploads',
  'site_content',
  'seo_page_templates',
  'coupons',
  'seo_pages',
  'blog_posts',
];

/** Renders one value as a literal Postgres will accept. */
const literal = (value, type) => {
  if (value === null || value === undefined) return 'NULL';

  switch (type) {
    case 'bytea':
      // Buffers go out as hex, which round-trips exactly and stays on one line.
      return `'\\x${value.toString('hex')}'::bytea`;
    case 'jsonb':
    case 'json':
      return `${quote(JSON.stringify(value))}::${type}`;
    case 'ARRAY':
      // node-postgres gives a JS array; Postgres wants an array literal.
      return `ARRAY[${value.map((v) => quote(String(v))).join(', ')}]::text[]`;
    case 'boolean':
      return value ? 'TRUE' : 'FALSE';
    case 'integer':
    case 'bigint':
    case 'smallint':
    case 'numeric':
    case 'real':
    case 'double precision':
      return String(value);
    default:
      if (value instanceof Date) return quote(value.toISOString());
      if (typeof value === 'object') return `${quote(JSON.stringify(value))}::jsonb`;
      return quote(String(value));
  }
};

/** Dollar-quoting would be fragile inside generated SQL; escape instead. */
const quote = (s) => `'${s.replace(/'/g, "''")}'`;

const run = async () => {
  const parts = [];
  parts.push('-- ORIVIDA store catalogue.');
  parts.push('-- Generated by `npm run db:export` — do not edit by hand.');
  parts.push(`-- Snapshot taken ${new Date().toISOString()}`);
  parts.push('--');
  parts.push('-- Load with `npm run db:seed-catalogue`, which applies the schema first.');
  parts.push('-- Contains store content only: no customers, orders or carts.');
  parts.push('');
  parts.push('BEGIN;');
  parts.push('');

  let grandTotal = 0;

  for (const table of TABLES) {
    const columns = await query(
      `SELECT column_name, data_type FROM information_schema.columns
        WHERE table_name = $1 AND table_schema = 'public'
        ORDER BY ordinal_position`,
      [table]
    );
    if (columns.rowCount === 0) {
      console.log(`  skipped ${table} (not in this schema)`);
      continue;
    }

    const names = columns.rows.map((c) => c.column_name);
    const types = Object.fromEntries(columns.rows.map((c) => [c.column_name, c.data_type]));

    // Not every table is keyed on id — site_content is keyed on its key
    // column — so order by whatever the first column happens to be.
    const orderBy = names.includes('id') ? 'id' : names[0];
    const rows = await query(`SELECT * FROM "${table}" ORDER BY "${orderBy}"`);
    console.log(`  ${String(rows.rowCount).padStart(4)}  ${table}`);
    grandTotal += rows.rowCount;

    // Idempotent: re-running the seed replaces the content rather than
    // erroring on duplicate keys or silently doubling it.
    parts.push(`-- ${table} (${rows.rowCount} rows)`);
    parts.push(`DELETE FROM "${table}";`);

    for (const row of rows.rows) {
      const values = names.map((n) => literal(row[n], types[n]));
      parts.push(
        `INSERT INTO "${table}" (${names.map((n) => `"${n}"`).join(', ')}) VALUES (${values.join(', ')});`
      );
    }
    parts.push('');
  }

  // Rows carry explicit ids, which leaves SERIAL sequences at 1 — the next
  // admin-created row then collides. Realign every sequence to its column.
  parts.push('-- Realign sequences so the next insert does not collide.');
  parts.push(`DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT c.relname AS seq, t.relname AS tbl, a.attname AS col
      FROM pg_class c
      JOIN pg_depend d ON d.objid = c.oid AND d.deptype = 'a'
      JOIN pg_class t ON t.oid = d.refobjid
      JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
     WHERE c.relkind = 'S'
  LOOP
    EXECUTE format('SELECT setval(%L, COALESCE((SELECT MAX(%I) FROM %I), 0) + 1, false)',
                   r.seq, r.col, r.tbl);
  END LOOP;
END $$;`);
  parts.push('');
  parts.push('COMMIT;');
  parts.push('');

  fs.writeFileSync(OUT, parts.join('\n'));
  const kb = Math.round(fs.statSync(OUT).size / 1024);
  console.log(`\n  ${grandTotal} rows -> ${path.relative(process.cwd(), OUT)} (${kb} KB)\n`);

  await pool.end();
};

run().catch(async (error) => {
  console.error('Export failed:', error.message);
  await pool.end().catch(() => {});
  process.exit(1);
});
